# Generated by Django 5.1.1 on 2024-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='c1_connected',
            field=models.BooleanField(default=False),
        ),
    ]
